query getMerchantSearch(
  $filter: merchant_bool_exp
  $limit: Int
  $offset: Int
  $order: [merchant_order_by!]
) {
  merchant(where: $filter, limit: $limit, offset: $offset, order_by: $order) {
    id
    first_name
    last_name
    phone_number
    user_id
  }
}
