query getCompanyCustomers(
  $companyId: uuid!
  $limit: Int
  $offset: Int
  $filter: company_customer_bool_exp = {}
) {
  company_customer(
    where: { _and: [{ company: { _eq: $companyId } }, $filter] }
    limit: $limit
    offset: $offset
    order_by: [{ created_at: desc }]
  ) {
    id
    created_at
    customer
    company
    branch
    customerByCustomer {
      id
      first_name
      last_name
      phone_number
    }
    branchByBranch {
      id
      name
    }
  }
  total: company_customer_aggregate(
    where: { _and: [{ company: { _eq: $companyId } }, $filter] }
  ) {
    aggregate {
      count
    }
  }
}