query getInvestors(
  $filter: investor_bool_exp
  $limit: Int
  $offset: Int
  $order: [investor_order_by!]
) {
  investor(where: $filter, limit: $limit, offset: $offset, order_by: $order) {
    id
    first_name
    last_name
    address
    created_at
    phone_number
    user_id
    user {
      id
      first_name
      last_name
      is_active
      email
      phone
      profile_picture
      telegram_user_name
    }
  }
  investor_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
